# coding=utf-8
__author__ = 'lijinde-lhq'
from mongoengine import *

connect('mydb', host='localhost', port=27017)


class Organ(Document):
    org_id = IntField(min_value=0, max_value=99999999999, required=True)
    org_parent_name = StringField(max_length=50, required=True)
    org_parent_id = IntField(min_value=0, max_value=99999999999, required=True)
    org_tree_level = IntField(min_value=0, max_value=99)
    org_station_flag = IntField(min_value=0, max_value=1)
    org_linkman = StringField(max_length=50)
    org_linkman_mobile = IntField(min_value=10000000000, max_value=99999999999)
    org_linkman_qq = StringField(max_length=20)
    org_manager = StringField(max_length=50, required=True)
    org_manager_cert_number = StringField(max_length=20, required=True)
    org_manager_mobile = IntField(min_value=10000000000, max_value=99999999999,required=True)
    org_name = StringField(max_length=100, required=True)
    org_status = IntField(min_value=0, max_value=1)
    org_belong_name = StringField(max_length=100)
    org_belong_type = IntField(min_value=1, max_value=4)
    org_type = IntField(min_value=1, max_value=5)
    org_manager_unit = StringField(max_length=200)
    org_build_date = DateTimeField()
    org_province = IntField(min_value=0, max_value=99999999999, required=True)
    org_city = IntField(min_value=0, max_value=99999999999, required=True)
    org_district = IntField(min_value=0, max_value=99999999999, required=True)
    org_street = IntField(min_value=0, max_value=99999999999, required=True)
    org_committee = IntField(min_value=0, max_value=99999999999, required=True)
    org_address = StringField(max_length=100, required=True)
    org_hour = DecimalField(min_value=0.00, max_value=999999999.99, precision=2, default=0.00, required=True)
    org_member = IntField(min_value=0, max_value=99999999999, required=True)
    org_introduce = StringField(max_length=6000, required=True)
    create_time = DateTimeField()
    org_service_type = StringField(max_length=100)
    org_record = IntField(min_value=0, max_value=3)
    org_record_name = StringField(max_length=60)
    createuserid = StringField(max_length=50)
    system_code = IntField(min_value=0, max_value=99999999999)
